### ISSUE TITLE
Hi!!

### ISSUE THREAD

**Issue by CT-40** [shaicoin/shaicoin#2]
How to mine? 
What algo?

Thanks!

**Comment by shaicoin** [comment]
Making a medium article right now that hopefully explains it.

Its the ShaiHive algo which is custom made. Essentially Hamiltonian graph search coupled with sha256 this Hamiltonian certificate is stored on the block header to easily verify the graph traversal.

Jump into discord if you have further questions.

https://discord.gg/vdycT2uDuR
